version: '3'

services:
  db:
    container_name: mysqldb
    # build: ../DB/
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: cp23ssi3
      MYSQL_DATABASE: internhub
      MYSQL_USER: root
      MYSQL_PASSWORD: cp23ssi3
    ports: 
      - "5173:3306"
    volumes:
      - ../DB:/docker-entrypoint-initdb.d
      - ../DB/data:/var/lib/mysql
      - ../DB/my.cnf:/etc/mysql/my.cnf
    restart: on-failure

  backend:
    container_name: backend
    depends_on:
      - db
    build: ../Backend/
    environment:
      - DB_HOST=db
      - DB_USER=dev
      - DB_PASSWORD=0000
      - DB_NAME=internhub
      - DB_PORT=3306
    restart: on-failure
  frontend:
    container_name: frontend
    depends_on:
      - backend
      - db
    image: node:latest
    build: ../Frontend
    restart: on-failure
  reverse-proxy:
    container_name: reverse-proxy
    depends_on:
      - frontend
    ports:
      - 8080:8080
      - "80:80"
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    restart: on-failure
  

