version: '3.3'

services:
  mysqldb:
    container_name: mysqldb
    # build: ../DB/
    # image: mysql/mysql-server:8.0.26
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: cp23ssi3
      MYSQL_DATABASE: internhub
      # MYSQL_USER: root
      # MYSQL_PASSWORD: cp23ssi3
    ports:
      - 5173:3306
    volumes:
      - ../DB:/docker-entrypoint-initdb.d
      - ../DB/data:/var/lib/mysql
      # - ../DB/my.cnf:/etc/mysql/my.cnf
    restart: on-failure
    # networks:
    #   - db_network

  backend:
    container_name: backend
    depends_on:
      - mysqldb
    build: ../Backend/
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/internhub
    # - DB_HOST=cp23ssi3.sit.kmutt.ac.th
    # - DB_USER=root
    # - DB_PASSWORD=cp23ssi3
    # - DB_NAME=internhub
    # - DB_PORT=3306
    # environment:
    # SPRING_APPLICATION_JSON: '{
    #   "spring.datasource.driver-class-name":"com.mysql.cj.jdbc.Driver",
    #   "spring.datasource.username" : "root",
    #   "spring.datasource.password" : "cp23ssi3",
    #   "spring.datasource.url" : "jdbc:mysql://localhost:5173/internhub?allowPublicKeyRetrieval=true&useSSL=false",
    #   "spring.jpa.hibernate.ddl-auto" : "update",
    #   "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
    #   "spring.jpa.database-platform" : "org.hibernate.dialect.MySQL5InnoDBDialect"
    #   }'
    volumes:
      - .m2:/root/.m2
    # links:
    #   - mysqldb
  # stdin_open: true
  # tty: true
  # networks:
  #   - be_network

  frontend:
    container_name: frontend
    depends_on:
      - backend
      - mysqldb
    ports:
      - 80:3000
    image: node:latest
    build: ../Frontend
    restart: on-failure
  # links:
  #   - backend

  # reverse-proxy:
  #   container_name: reverse-proxy
  #   depends_on:
  #     - frontend
  #   ports:
  #     - 8080:8080
  #     - 80:80
  #   image: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   restart: on-failure
  # links:
  #   - frontend
# networks:
#   db_network:
#     driver: bridge
#   be_network:
#     driver: bridge
