version: '3.3'

services:
  mysqldb:
    container_name: mysqldb
    # build: ../DB/
    # image: mysql/mysql-server:8.0.26
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: cp23ssi3
      MYSQL_DATABASE: internhub
      MYSQL_USER: root
      MYSQL_HOST: cp23ssi3.sit.kmutt.ac.th
    ports:
      - 3306:3306
    volumes:
      - ../DB:/docker-entrypoint-initdb.d
      - ../DB/data:/var/lib/mysql
      # - ../DB/my.cnf:/etc/mysql/my.cnf
    restart: on-failure
    # networks:
    #   - db_network

  backend:
    container_name: backend
    depends_on:
      - mysqldb
    build: ../Backend/
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - .m2:/root/.m2
    environment:
      - spring.datasource.url=jdbc:mysql://10.4.85.39:3306/internhub

  frontend:
    container_name: frontend
    depends_on:
      - backend
      - mysqldb
    ports:
      - 80:3000
    image: node:latest
    build: ../Frontend
    restart: on-failure

  # reverse-proxy:
  #   container_name: reverse-proxy
  #   depends_on:
  #     - frontend
  #   ports:
  #     - 8080:8080
  #     - 80:3000
  #   image: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   restart: on-failure
  # links:
  #   - frontend
# networks:
#   db_network:
#     driver: bridge
#   be_network:
#     driver: bridge
